name: Run locale check

on:
  push:
    tags:
      - v*
    paths:
      - 'public/locales/**'
  pull_request:
    paths:
      - 'public/locales/**'

jobs:
  locale-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run checker.js
        run: node public/checker.js